<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'StautRH\\' => array($baseDir . '/source'),
    'MatthiasMullie\\PathConverter\\' => array($vendorDir . '/matthiasmullie/path-converter/src'),
    'MatthiasMullie\\Minify\\' => array($vendorDir . '/matthiasmullie/minify/src'),
    'League\\Plates\\' => array($vendorDir . '/league/plates/src'),
    'CoffeeCode\\Router\\' => array($vendorDir . '/coffeecode/router/src'),
    'CoffeeCode\\Paginator\\' => array($vendorDir . '/coffeecode/paginator/src'),
    'CoffeeCode\\Optimizer\\' => array($vendorDir . '/coffeecode/optimizer/src'),
);
